services:
  db:
    image: mysql:8.4.3
    container_name: mysql-library
    environment:
      # YES I KNOW THIS IS NOT SECURE, BUT THIS IS A DEMO
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
volumes:
  db_data:
